POST http://localhost:8080/api/svgs
Content-Type: application/json

{
  "name" : "Test Svg",
  "description" : "Hardcoded test value"
}

###
GET http://localhost:8080/api/svgs

###

GET http://localhost:8080/api/svgs/283973d2-de07-499c-900a-e4a3881a2d90

###
DELETE http://localhost:8080/api/svgs/283973d2-de07-499c-900a-e4a3881a2d90

###